# Generated by Django 4.2.16 on 2024-10-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='description',
        ),
        migrations.AddField(
            model_name='home',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
