# Generated by Django 4.2.16 on 2024-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_home_description_home_email_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='skill_images/')),
            ],
        ),
    ]
