# Generated by Django 4.2.16 on 2024-10-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='project_description',
        ),
    ]
